server:
  port: 8080
spring:
  profiles:
    active: docker
  datasource:
    url: jdbc:mysql://localhost:3306/chat_db?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
